/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as QuestionsIndexImport } from './routes/questions/index'
import { Route as UsersUserIdImport } from './routes/users/$userId'
import { Route as QuestionsCreateImport } from './routes/questions/create'
import { Route as PostsCreateImport } from './routes/posts/create'
import { Route as PostsPostIdImport } from './routes/posts/$postId'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as UsersMeIndexImport } from './routes/users/me/index'
import { Route as UsersMePostsIndexImport } from './routes/users/me/posts/index'
import { Route as UsersMePostsPostIdImport } from './routes/users/me/posts/$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const QuestionsIndexRoute = QuestionsIndexImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

const QuestionsCreateRoute = QuestionsCreateImport.update({
  id: '/questions/create',
  path: '/questions/create',
  getParentRoute: () => rootRoute,
} as any)

const PostsCreateRoute = PostsCreateImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const UsersMeIndexRoute = UsersMeIndexImport.update({
  id: '/users/me/',
  path: '/users/me/',
  getParentRoute: () => rootRoute,
} as any)

const UsersMePostsIndexRoute = UsersMePostsIndexImport.update({
  id: '/users/me/posts/',
  path: '/users/me/posts/',
  getParentRoute: () => rootRoute,
} as any)

const UsersMePostsPostIdRoute = UsersMePostsPostIdImport.update({
  id: '/users/me/posts/$postId',
  path: '/users/me/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/create': {
      id: '/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof PostsCreateImport
      parentRoute: typeof rootRoute
    }
    '/questions/create': {
      id: '/questions/create'
      path: '/questions/create'
      fullPath: '/questions/create'
      preLoaderRoute: typeof QuestionsCreateImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdImport
      parentRoute: typeof rootRoute
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/me/': {
      id: '/users/me/'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/me/posts/$postId': {
      id: '/users/me/posts/$postId'
      path: '/users/me/posts/$postId'
      fullPath: '/users/me/posts/$postId'
      preLoaderRoute: typeof UsersMePostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/users/me/posts/': {
      id: '/users/me/posts/'
      path: '/users/me/posts'
      fullPath: '/users/me/posts'
      preLoaderRoute: typeof UsersMePostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/create': typeof PostsCreateRoute
  '/questions/create': typeof QuestionsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/questions': typeof QuestionsIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/me': typeof UsersMeIndexRoute
  '/users/me/posts/$postId': typeof UsersMePostsPostIdRoute
  '/users/me/posts': typeof UsersMePostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/create': typeof PostsCreateRoute
  '/questions/create': typeof QuestionsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/questions': typeof QuestionsIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/me': typeof UsersMeIndexRoute
  '/users/me/posts/$postId': typeof UsersMePostsPostIdRoute
  '/users/me/posts': typeof UsersMePostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/create': typeof PostsCreateRoute
  '/questions/create': typeof QuestionsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/questions/': typeof QuestionsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/me/': typeof UsersMeIndexRoute
  '/users/me/posts/$postId': typeof UsersMePostsPostIdRoute
  '/users/me/posts/': typeof UsersMePostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/posts/$postId'
    | '/posts/create'
    | '/questions/create'
    | '/users/$userId'
    | '/questions'
    | '/users'
    | '/users/me'
    | '/users/me/posts/$postId'
    | '/users/me/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/posts/$postId'
    | '/posts/create'
    | '/questions/create'
    | '/users/$userId'
    | '/questions'
    | '/users'
    | '/users/me'
    | '/users/me/posts/$postId'
    | '/users/me/posts'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/posts/$postId'
    | '/posts/create'
    | '/questions/create'
    | '/users/$userId'
    | '/questions/'
    | '/users/'
    | '/users/me/'
    | '/users/me/posts/$postId'
    | '/users/me/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsCreateRoute: typeof PostsCreateRoute
  QuestionsCreateRoute: typeof QuestionsCreateRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersMeIndexRoute: typeof UsersMeIndexRoute
  UsersMePostsPostIdRoute: typeof UsersMePostsPostIdRoute
  UsersMePostsIndexRoute: typeof UsersMePostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsCreateRoute: PostsCreateRoute,
  QuestionsCreateRoute: QuestionsCreateRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersMeIndexRoute: UsersMeIndexRoute,
  UsersMePostsPostIdRoute: UsersMePostsPostIdRoute,
  UsersMePostsIndexRoute: UsersMePostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/register",
        "/posts/$postId",
        "/posts/create",
        "/questions/create",
        "/users/$userId",
        "/questions/",
        "/users/",
        "/users/me/",
        "/users/me/posts/$postId",
        "/users/me/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx"
    },
    "/posts/create": {
      "filePath": "posts/create.tsx"
    },
    "/questions/create": {
      "filePath": "questions/create.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    },
    "/questions/": {
      "filePath": "questions/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/users/me/": {
      "filePath": "users/me/index.tsx"
    },
    "/users/me/posts/$postId": {
      "filePath": "users/me/posts/$postId.tsx"
    },
    "/users/me/posts/": {
      "filePath": "users/me/posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
